---

- include_vars: "{{ansible_distribution}}.yml"

- name: Install dependencies
  apt: name=python3-pycurl

- name: Install nginx
  apt: name=nginx state=latest
  
  notify:
    - restart nginx  

- name: Install Dependencies
  apt: name={{item}}
  with_items: [ nginx, python3-passlib ] 
